# Generated by Django 4.0 on 2022-01-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment', models.AutoField(primary_key=True, serialize=False)),
                ('is_valid', models.IntegerField()),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ok', models.IntegerField()),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment', models.AutoField(primary_key=True, serialize=False)),
                ('serial_num', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['serial_num'],
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('general', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'general',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('make', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.IntegerField(unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'make',
            },
        ),
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('request', models.AutoField(primary_key=True, serialize=False)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request',
                'ordering': ['-date_out'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.AutoField(primary_key=True, serialize=False)),
                ('taken', models.IntegerField()),
                ('date', models.DateField(unique=True)),
                ('general', models.ForeignKey(blank=True, db_column='general', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.general')),
                ('request', models.ForeignKey(blank=True, db_column='request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.requestlist')),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
