# Generated by Django 4.0 on 2022-01-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('condition', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('equipment', models.ForeignKey(blank=True, db_column='equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.equipment')),
                ('request', models.ForeignKey(blank=True, db_column='request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.requestlist')),
            ],
            options={
                'db_table': 'request_details',
                'unique_together': {('request', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
