# Generated by Django 4.0 on 2022-01-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_requestdetails_delete_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestdetails',
            unique_together={('equipment', 'date')},
        ),
    ]
