# Generated by Django 4.0 on 2022-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_requestdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestdetails',
            unique_together={('equipment',)},
        ),
    ]
