# Generated by Django 4.0 on 2022-01-17 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_requestdetails_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('return_detail', models.AutoField(primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Condtition',
            fields=[
                ('condtition', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(unique=True)),
                ('description', models.TextField(max_length=255)),
                ('equipment', models.ForeignKey(blank=True, db_column='equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='requestdetails',
            name='return_detail',
            field=models.ForeignKey(blank=True, db_column='return_detail', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.returndetail'),
        ),
    ]
