# Generated by Django 4.0 on 2022-01-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_returndetail_condtition_requestdetails_return_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestDetails',
            new_name='RequestDetail',
        ),
    ]
