# Generated by Django 4.0 on 2022-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_requestdetail_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestDetail',
            new_name='RequestDetails',
        ),
        migrations.AlterModelTable(
            name='requestdetails',
            table='requestDetail',
        ),
    ]
