# Generated by Django 4.0 on 2022-01-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_requestdetail_requestdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condtition',
            table='condition',
        ),
        migrations.AlterModelTable(
            name='returndetail',
            table='returnDetail',
        ),
    ]
