# Generated by Django 4.0 on 2022-01-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_condtition_table_alter_returndetail_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condtition',
            old_name='condtition',
            new_name='condition',
        ),
    ]
