# Generated by Django 4.0 on 2022-01-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_rename_condtition_condtition_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('situation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(unique=True)),
                ('description', models.TextField(max_length=255)),
                ('equipment', models.ForeignKey(blank=True, db_column='equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.equipment')),
            ],
            options={
                'db_table': 'situation',
            },
        ),
        migrations.DeleteModel(
            name='Condtition',
        ),
    ]
