# Generated by Django 4.0 on 2022-01-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.IntegerField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onboarding.department')),
            ],
            options={
                'db_table': 'student',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AttachLec',
            fields=[
                ('attach_lec', models.AutoField(primary_key=True, serialize=False)),
                ('is_valid', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onboarding.department')),
                ('lecturer', models.ForeignKey(blank=True, db_column='lecturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onboarding.lecturer')),
            ],
            options={
                'db_table': 'attach_lec',
                'unique_together': {('date', 'lecturer', 'department')},
            },
        ),
    ]
